---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/cmd/webhook"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      docker-webhook:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/cmd/basicauth"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      docker-bacsicauth:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/cmd/githubauth"
    schedule:
      interval: "monthly"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      docker-bacsicauth:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      gomod:
        patterns:
          - "*"
