---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "sidecar-injector.fullname" . }}
webhooks:
  - name: sidecar-injector.ricoberger.de
    clientConfig:
      caBundle: Cg==
      service:
        name: {{ include "sidecar-injector.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    {{- with .Values.namespaceSelector }}
    namespaceSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 10
    failurePolicy: {{ .Values.failurePolicy }}
