---
name: Continuous Delivery

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - directory: "webhook"
            image: "ghcr.io/${{ github.repository }}"
          - directory: "basicauth"
            image: "ghcr.io/${{ github.repository }}/basicauth"
          - directory: "githubauth"
            image: "ghcr.io/${{ github.repository }}/githubauth"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.image.image }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image (webhook)
        id: docker_build_webhook
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./cmd/${{ matrix.image.directory }}/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  helm:
    name: Helm
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set Version
        id: version
        run: |
          echo VERSION=$(yq -r .version ./charts/sidecar-injector/Chart.yaml) >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Package and Push Helm Chart
        run: |
          helm package ./charts/sidecar-injector --version ${{ env.VERSION }}
          helm push ./sidecar-injector-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
